URL_MAP = {
    "open morning": "https://www.morehouse.org.uk/admissions/our-open-events/",
    "open day": "https://www.morehouse.org.uk/admissions/our-open-events/",
    "visit us": "https://www.morehouse.org.uk/admissions/our-open-events/",
    "school tour": "https://www.morehouse.org.uk/admissions/our-open-events/",
    "enquire": "https://www.morehouse.org.uk/admissions/enquiry/",
    "fees": "https://www.morehouse.org.uk/admissions/fees/",
    "term dates": "https://www.morehouse.org.uk/news-and-calendar/term-dates/",
    "scholarship": "https://www.morehouse.org.uk/admissions/scholarships-and-bursaries/",
    "bursary": "https://www.morehouse.org.uk/admissions/scholarships-and-bursaries/",
    "learning support": "https://www.morehouse.org.uk/learning/learning-support/",
    "academic stretch": "https://www.morehouse.org.uk/learning/academic-stretch/",
    "sixth form": "https://www.morehouse.org.uk/learning/sixth-form/",
    "subjects": "https://www.morehouse.org.uk/learning/subjects/",
    "creative suite": "https://www.morehouse.org.uk/learning/our-creative-suite/",
    "results": "https://www.morehouse.org.uk/learning/results-and-destinations/",
    "co-curricular": "https://www.morehouse.org.uk/beyond-the-classroom/co-curricular-programme/",
    "sport": "https://www.morehouse.org.uk/beyond-the-classroom/sport/",
    "faith": "https://www.morehouse.org.uk/beyond-the-classroom/faith-life/",
    "city curriculum": "https://www.morehouse.org.uk/beyond-the-classroom/city-curriculum/",
    "be more": "https://www.morehouse.org.uk/learning/be-more/",
    "academic life": "https://www.morehouse.org.uk/learning/academic-life/",
    "joining": "https://www.morehouse.org.uk/admissions/joining-more-house/",
    "contact": "https://www.morehouse.org.uk/contact/",
}

